// <auto-generated />
using System;
using EatFit.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EatFit.Migrations
{
    [DbContext(typeof(FoodItemDbContext))]
    [Migration("20210913150843_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EatFit.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Breakfast",
                            Description = "The most important meal of the day !"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lunch",
                            Description = "The most heaviest meal of the day !"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Dinner",
                            Description = "The most light meal of the day !"
                        });
                });

            modelBuilder.Entity("EatFit.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Dinner",
                            Cost = 140,
                            ImageUrl = "/img/pasta.jpg",
                            IsVeg = true,
                            LongDescription = "Prepared with this and that",
                            Name = "Pasta",
                            Ratings = 3.3999999999999999,
                            ShortDescription = "Crispy and Spicy"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Breakfast",
                            Cost = 400,
                            ImageUrl = "/img/poha.jpg",
                            IsVeg = true,
                            LongDescription = "Prepared with this and that",
                            Name = "Poha",
                            Ratings = 4.4000000000000004,
                            ShortDescription = "Yummy "
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Dinner",
                            Cost = 1000,
                            ImageUrl = "/img/pizza.jpg",
                            IsVeg = true,
                            LongDescription = "Prepared with this and that",
                            Name = "Pizza",
                            Ratings = 4.0,
                            ShortDescription = "Spicy"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Lunch",
                            Cost = 3400,
                            ImageUrl = "/img/burger.jpg",
                            IsVeg = false,
                            LongDescription = "Prepared with this and that",
                            Name = "Burger",
                            Ratings = 5.0,
                            ShortDescription = " Spicy"
                        });
                });

            modelBuilder.Entity("EatFit.Models.ShoppingCartItems", b =>
                {
                    b.Property<int>("ShoppingCartItemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("foodItemId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemid");

                    b.HasIndex("foodItemId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("EatFit.Models.FoodItem", b =>
                {
                    b.HasOne("EatFit.Models.Category", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("EatFit.Models.ShoppingCartItems", b =>
                {
                    b.HasOne("EatFit.Models.FoodItem", "foodItem")
                        .WithMany()
                        .HasForeignKey("foodItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
